site_name: Python Project
nav:
  - Home: README.md
  - Contributing: contributing.md
theme:
  name: 'material'
repo_url: https://github.com/pycontw/pycon_archive_past_website
remote_branch: gh-pages
remote_name: origin
