name: Deploy PyConTW sites to branch

on: push

jobs:
  deploy-dev-pycontw-sites:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install -U pip pipenv
          pipenv install
      - name: Crawl Past PyConTW Websites
        run: |
          pipenv run python3 pycon_archive_past_website/pycon_archive_past_website.py -y 2016 --base https://tw.pycon.org
          pipenv run python3 pycon_archive_past_website/pycon_archive_past_website.py -y 2017 --base https://tw.pycon.org
          pipenv run python3 pycon_archive_past_website/pycon_archive_past_website.py -y 2018 --base https://tw.pycon.org
          pipenv run python3 pycon_archive_past_website/pycon_archive_past_website.py -y 2019 --base https://tw.pycon.org
          pipenv run python3 pycon_archive_past_website/pycon_archive_past_website.py -y 2020 --base https://tw.pycon.org
