name: Deploy PyConTW sites to branch

on:
  workflow_dispatch:
    inputs:
      year:
        description: The year of official website that haven't been archived e.g. "2021"
        required: true
      base_url:
        description: 'Dynamic base url for different domain e.g. "/pycon_archive_past_website"'
        required: true

jobs:
  deploy-dev-pycontw-sites:
    if:
      ${{github.event.inputs.year > 2020 }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "pycon_archive_past_website"
          token: '${{ secrets.GITHUB_TOKEN }}'
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install -U pip pipenv
          pipenv install
      - name: Crawl Past PyConTW Websites
        run: |
          pipenv run python3 main.py -y ${{github.event.inputs.year}} --base ${{github.event.inputs.base_url}}
          wait
          mkdir build; mv ${{github.event.inputs.year}} build/
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
