name: Deploy PyConTW sites to branch

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Dynamic base url for different domain'
        required: true

jobs:
  deploy-pycontw-sites:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install -U pip pipenv
          pipenv install
      - name: Crawl Past PyConTW Websites
        run: |
          pipenv run python3 main.py -y 2016 --base ${{github.event.inputs.base_url}} &
          pipenv run python3 main.py -y 2017 --base ${{github.event.inputs.base_url}} &
          pipenv run python3 main.py -y 2018 --base ${{github.event.inputs.base_url}} &
          pipenv run python3 main.py -y 2019 --base ${{github.event.inputs.base_url}} &
          pipenv run python3 main.py -y 2020 --base ${{github.event.inputs.base_url}} &
          wait
          mkdir build; mv 2016/ 2017/ 2018/ 2019/ 2020/ build/
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
